export const ACTION_TYPE = {
  LOG_IN: 'LOG_IN',
  LOG_IN_LOADING: 'LOG_IN_LOADING',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_ERROR: 'LOG_IN_ERROR',
  LOG_OUT: 'LOG_OUT',

  GET_VIDEOS: 'GET_VIDEOS',
  GET_VIDEOS_LOADING: 'GET_VIDEOS_LOADING',
  GET_VIDEOS_SUCCESS: 'GET_VIDEOS_SUCCESS',
  GET_VIDEOS_ERROR: 'GET_VIDEOS_ERROR',

  VOTE_VIDEO: 'VOTE_VIDEO',
  VOTE_VIDEO_SUCCESS: 'VOTE_VIDEO_SUCCESS',
  VOTE_VIDEO_ERROR: 'VOTE_VIDEO_ERROR',
};

export default {};
