export const ACTION_TYPE = {
  LOG_IN: 'LOG_IN',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_ERROR: 'LOG_IN_ERROR',
  LOG_OUT: 'LOG_OUT',

  GET_VIDEOS: 'GET_VIDEOS',
  GET_VIDEOS_LOADING: 'GET_VIDEOS_LOADING',
  GET_VIDEOS_SUCCESS: 'GET_VIDEOS_SUCCESS',
  GET_VIDEOS_ERROR: 'GET_VIDEOS_ERROR',
};

export default {};
